### ISSUE TITLE
useLink isn't included in VueRouterExports

### ISSUE THREAD

**Issue by zkulbeda** [posva/unplugin-vue-router#100]
`useLink` can't be auto imported, because it didn't specified in [VueRouterExports](https://github.com/posva/unplugin-vue-router/blob/main/src/index.ts#L184)

**Comment by posva** [comment]
This is intended as it’s important to keep auto imports to the strict minimal. You can check the unplugin auto import repo for reference.

Of course, you can add it to your vite confit if you use it very often

**Comment by zkulbeda** [comment]
So, from [README.md](https://github.com/posva/unplugin-vue-router/blob/main/README.md?plain=1#L164) it's not clear that VueRouterAutoImports has the strict minimal and can't be drop-in replacement, because the unplugin-auto-import [vue-router] preset (https://github.com/antfu/unplugin-auto-import/blob/main/src/presets/vue-router.ts) has other composables build-in.

**Comment by posva** [comment]
Ah, they changed it. I adapted the exports and the readme but `useLink()` is situational and sholudn't be in the auto imports array in my opinion, so I added a note on how to add it to the config

**Comment by zkulbeda** [comment]
Thanks!
