### ISSUE TITLE
handle `.page.vue` extension

### ISSUE THREAD

**Issue by stefanprobst** [posva/unplugin-vue-router#101]
when configuring the vite plugin with a `.page.vue` extension, the generated route config includes e.g. `/index.page` for `./src/pages/index.page.vue`:

```ts
// vite.config.ts
import vue from '@vitejs/plugin-vue'
import router from 'unplugin-vue-router/vite'
import { defineConfig } from 'vite'

export default defineConfig({
  plugins: [
    router({ dts: './routes.d.ts', extensions: ['.page.vue'] }),
    vue(),
  ],
})
```

```ts
// snippet from generated routes.d.ts
declare module 'vue-router/auto/routes' {
  export interface RouteNamedMap {
    '/index.page': RouteRecordInfo<
      '/index.page',
      '/index/page',
      Record<never, never>,
      Record<never, never>
    >
  }
}
```

**Comment by posva** [comment]
The . Here has a special meaning and is transformed to a slash

what are you expecting exactly?

**Comment by stefanprobst** [comment]
when i configure a file extension which includes a dot, e.g. `extensions: ["page.vue"]`, i would expect that this dot will be treated as being part of the file extension and not converted to a slash.

i guess this would mean that [`trimExtension`](https://github.com/posva/unplugin-vue-router/blob/main/src/core/utils.ts#L61) should not simply slice off everything after the last dot, but use the actual configured extensions.

**Comment by posva** [comment]
I see. What is the idea of having `.page.vue` exactly? Is it more of a domain-based file organization, something similar to Next.js and SvelteKit conventions?

**Comment by stefanprobst** [comment]
> Is it more of a domain-based file organization, something similar to Next.js and SvelteKit conventions?

yep, exactly.
