### ISSUE TITLE
the new version breaks definePage naming 

### ISSUE THREAD

**Issue by zynth17** [posva/unplugin-vue-router#116]
updated to latest 0.3.1 and it breaks the page with `definePage` macros.

<img width="1376" alt="image" src="https://user-images.githubusercontent.com/45350572/211231461-da6a43c3-7fdf-4cea-a88e-cd988f11d714.png">

**Comment by posva** [comment]
I don’t understand. Please post more info and don’t use screenshots for code, directly paste the code

**Comment by zynth17** [comment]
> I don’t understand. Please post more info and don’t use screenshots for code, directly paste the code

my apologies, here is a repro
https://github.com/zynth17/unplugin-vue-router-bug-dynamic-path
