### ISSUE TITLE
change default routes folder to be pages folder

### ISSUE THREAD

**Issue by zynth17** [posva/unplugin-vue-router#12]
isn't it a good practice to have the default folder to be `pages` instead of `routes` ?
as it will not make any confusion with nuxt?

**Comment by zynth17** [comment]
> There isn't such "good practice". Default naming can be changed but note this is already configurable through the routesFolder option

well i agree with there isn't such good practice, but it just better to follow out naming convention out there. and yes i'm aware of this can be configureable but having to set it everytime we create new project to follow these convention isn't also a good thing. well this just a suggestion :D 
anyway thankyou for this package, will start migrating tomorrow.

**Comment by posva** [comment]
Let me know how it goes 👀

**Comment by posva** [comment]
By default, `useRoute()` (from `@vue-router`) returns an union of all possible routes. You can add `if (route.name === '...')` to hint TS about the actual route. If you use `route.name.includes()` then TS won't be able to hint, it has to be an `if`. Maybe some custom made `includes()` with types would hint better TS

**Comment by posva** [comment]
you can pass a generic to useRoute (or an argument):

```ts
useRoute<'/users/[id]'>() // -> it's the id route
useRoute('/users/[id]') // same as above
useRoute<'/users/[id]' | '/users/[id]/edit'>() // -> one of them
```

**Comment by zynth17** [comment]
> you can pass a generic to useRoute (or an argument):
> 
> ```ts
> useRoute<'/users/[id]'>() // -> it's the id route
> useRoute('/users/[id]') // same as above
> useRoute<'/users/[id]' | '/users/[id]/edit'>() // -> one of them
> ```

i will try this one, but i hate the idea passing an exact string as a generic type here, is it possible to use RouteNameMap as the type? and how do we got the exact type of this route using RouteNameMap? is it possible?

**Comment by posva** [comment]
The argument should autocomplete, that's the whole point, it's easy to type 😄

I would recommend you to take a look into the generated `d.ts` to learn more about the generated types and how to import them, especially the 

```ts
export type Route<Name extends keyof RouteNamedMap> = RouteLocationNormalizedLoadedTypedList<RouteNamedMap>[Name]
```

**Comment by zynth17** [comment]
> The argument should autocomplete, that's the whole point, it's easy to type 😄

i tried and it doesn't have autocomplete that's why im saying in typing it 😂 or maybe my vscode broken. ill try it again tomorrow 😂

> I would recommend you to take a look into the generated `d.ts` to learn more about the generated types and how to import them, especially the 
> 
> 
> 
> ```ts
> 
> export type Route<Name extends keyof RouteNamedMap> = RouteLocationNormalizedLoadedTypedList<RouteNamedMap>[Name]
> 
> ```

noted. i will try to deep dive the .d.ts file, so far im just checking the generated route name. thanks.

**Comment by posva** [comment]
But you shouldn't need to go that far for simple cases. Are you importing from `@vue-router`?

**Comment by zynth17** [comment]
> But you shouldn't need to go that far for simple cases. Are you importing from `@vue-router`?

you mean the useRoute? do i need to import it from @vue-router?

**Comment by zynth17** [comment]
> Yes, everything should be imported from there

tried and still does not work, the repro i attach on #20 can also be the repro for this

**Comment by zynth17** [comment]
btw, using [auto-import](https://github.com/antfu/unplugin-auto-import) and setting up the auto import to autoimporting `vue-router` is also infering the type.

here it's auto infering the type to `@vue-router` type.
![image](https://user-images.githubusercontent.com/45350572/177486115-f90755d3-421f-430c-8598-2562753814c8.png)

vite.config.ts
![image](https://user-images.githubusercontent.com/45350572/177485748-3bd51346-91dd-44af-baa5-5c92efc14ede.png)

**Comment by posva** [comment]
Let's keep this conversation in the other issue, it's getting confusing 😆 

BTW: you cannot autoimport from 'vue-router', it has to be from `@vue-router` to get the automatic types. I think we could expose a preset here.

**Comment by zynth17** [comment]
> Let's keep this conversation in the other issue, it's getting confusing 😆
sure, 😂
 
> BTW: you cannot autoimport from 'vue-router', it has to be from `@vue-router` to get the automatic types. I think we could expose a preset here.
great idea!

**Comment by posva** [comment]
I'm adding this in the next release: changing the default from `src/routes` to `src/pages` as a breaking change. I think it's better as it's just one step less to do.

**Comment by zynth17** [comment]
> I'm adding this in the next release: changing the default from `src/routes` to `src/pages` as a breaking change. I think it's better as it's just one step less to do.

finally!! 🔥🔥 thankyou!!
