### ISSUE TITLE
Comparison with vite-plugin-pages?

### ISSUE THREAD

**Issue by Sjoerd82** [posva/unplugin-vue-router#124]
I had a brief run-in with Nuxt3, and loved their file based routing. Naturally I'm now checking to see if file based routing is available for "regular" Vue. In the past I had already seen it being used in the Vitesse starter, so my hopes are up.

Vitesse uses [vite-plugin-pages](https://github.com/hannoeru/vite-plugin-pages), which you also reference in the README.

How is this `unplugin-vue-router` different from vite-plugin-pages?
Help me choose! 👍 :-)

**Comment by posva** [comment]
in short:

- types routes
- specific to Vue router
- Data loaders
- Experimental

**Comment by husayt** [comment]
would be great to provide a short guidnace in the readme, about the advantage of each library and when to use. That will help to avoid unnecessary bickering as well, as will make clear what to use when.

Thanks.
