### ISSUE TITLE
cannot find @vue-router module

### ISSUE THREAD

**Issue by zynth17** [posva/unplugin-vue-router#15]
trying to migrate this morning, but got stuck because of this

![image](https://user-images.githubusercontent.com/45350572/177236405-4c4a4b16-b1d6-4ea6-bd29-21d5e1a4ec53.png)

also is it possible to get the generated routes?
with [vite-plugin-vue-layouts](https://github.com/JohnCampionJr/vite-plugin-vue-layouts)
we need the generated routes to bootstrap the vite plugin layouts itself.

**Comment by zynth17** [comment]
oh my bad, seems like i'm missing the requirement to upgrade to vue-router 4.1

**Comment by posva** [comment]
You seem to have missed the configuration part at https://github.com/posva/unplugin-vue-router#typescript

About the layouts plugin, it should be possible to make it work with the `extendRoutes()` option: `extendRoutes: routes => setupLayouts(routes)`

**Comment by zynth17** [comment]
> You seem to have missed the configuration part at https://github.com/posva/unplugin-vue-router#typescript
> 
> About the layouts plugin, it should be possible to make it work with the `extendRoutes()` option: `extendRoutes: routes => setupLayouts(routes)`

oh right i missed that section. 
also is there any way to typing the route meta type? for all route.

**Comment by posva** [comment]
Yes, with RouteMeta, like shown in vue router docs
