### ISSUE TITLE
Translation of meta-data

### ISSUE THREAD

**Issue by SimonSimCity** [posva/unplugin-vue-router#150]
I would like to integrate `i18n` to my meta-data. Before using this plugin, I could just write whatever code I wanted into my `router.ts` file, but this doesn't seem possible here... 

[In the docs](https://github.com/posva/unplugin-vue-router#definepage-in-script) you write:
> Note you cannot use variables in `definePage()` as its passed parameter gets extracted at build time and is removed from `<script setup>`. You can also use [the <route> block](https://github.com/posva/unplugin-vue-router#sfc-route-custom-block) which allows other formats like yaml.

... and inside the documentation for the <route> block, it's written it only supports `JSON5`, `YAML` and `JSON` ... So it doesn't seem to be possible to use anything flexible ...

Are there ways of how I could realize my idea and still use something in the direction of `$t("my-key")` so my eslint will pick it up as required translation? (I use https://github.com/intlify/eslint-plugin-vue-i18n)

**Comment by posva** [comment]
In your case you can also pass the key and translate when you read it

**Comment by SimonSimCity** [comment]
Worked around this issue by using a store for setting this value when rendering a page 😊 Just have to keep in mind to set this value on every route ☺️
