### ISSUE TITLE
Added files are not filtered out

### ISSUE THREAD

**Issue by posva** [posva/unplugin-vue-router#165]
When adding files while in dev mode, they do not get filtered out through the watcher

**Comment by Allezk** [comment]
I ran in to a bug while creating a new route for example test/[testid] but I wanted it to be test/[testId] with a capital i. After renaming the file it created two routes and while in dev capital i worked but when building it did not. Had to rename it to [testid] 

Is it related to this issue or should I open a new one?

**Comment by posva** [comment]
Related
