### ISSUE TITLE
Feature Request: generate single route when possible

### ISSUE THREAD

**Issue by ModyQyW** [posva/unplugin-vue-router#166]
Hi! Thanks for your work first! 👍

I am trying to migrate my project from `vite-plugin-pages` and `vite-plugin-vue-layouts` to `unplugin-vue-router` and `vite-plugin-vue-layouts`. And I am kind of stuck now.

Given the folder structure

```json
src/pages/
├── users/
   ├── helpers
   │  └── index.ts
   ├── components
   │  └── A.vue
   └── index.vue
```

The `src/pages/users/index.vue` `<route>` block:

```vue
<route lang="yaml">
meta:
  layout: simple
  hidden: true
</route>
```

The `vite.config.ts`:

```typescript
// vite.config.ts
import VueRouter from 'unplugin-vue-router/vite'

export default defineConfig({
  plugins: [
    VueRouter({
      exclude: '**/components/**/*.vue'
    }),
    Vue(),
  ],
})
```

The plugin gives this `routes` array.

```typescript
const routes = [
  {
    "path": "/sign-in",
    "children": [
      {
        "path": "",
        "name": "/sign-in/",
        "meta": {
          "layout": "simple",
          "hidden": true
        }
      }
    ]
  }
]
```

I think we can generate a single route in this case.

```typescript
const routes = [
  {
    "path": "/sign-in",
    "meta": {
        "layout": "simple",
        "hidden": true
     }
  }
]
```

The routes are simpler. And it can bring better compatibility with `vite-plugin-vue-layouts`. 

Please consider supporting this. If you think it is nice to have, I would like to send a PR for this. Thanks! 🙏

**Comment by posva** [comment]
If this is just to work correctly with the layouts plugin, I remember there is an open issue there. That’s where the PR should be sent 🙌

**Comment by ModyQyW** [comment]
Thanks for your reply! I will check what I can do.
