### ISSUE TITLE
RangeError when running multiple requests

### ISSUE THREAD

**Issue by posva** [posva/unplugin-vue-router#173]
- https://stackblitz.com/edit/vitejs-vite-pmdkkm

- Click Test 1, wait, then Test 2, wait, then test 1

It outputs a RangeError. Maybe the wrong route reference is used somewhere

From https://github.com/posva/unplugin-vue-router/discussions/169

**Comment by minht11** [comment]
I am trying to patch this locally for myself and it seems, shouldFetchAgain entry can resursively point to itself.

<img width="636" alt="Screenshot 2023-07-18 at 02 45 28" src="https://github.com/posva/unplugin-vue-router/assets/8914032/2a67e926-ee01-4342-accd-c3e540f7aa39">


I am not sure if that is intended, but the quick fix could be to change this code

https://github.com/posva/unplugin-vue-router/blob/5d9f1086cbe884e8a5e065a0de92665ff6c87b76/src/data-fetching/defineLoader.ts#L301-L315

to check if entry and child entry are not the same

```ts
Array.from(entry.children).some((childEntry) => 
      entry !== childEntry && shouldFetchAgain(childEntry, route) 
     )
```
