### ISSUE TITLE
✨ Utility for route names like nuxt

### ISSUE THREAD

**Issue by jd-solanki** [posva/unplugin-vue-router#182]
Hey 👋🏻 

I checked `getRouteName` and we can only get two patterns. We are building app for both Vue & Nuxt and we have to replace all the route names from `/name/some` to `name-some`. Can `unplugin-vue-router` provide nuxt like names for the generated routes?

Thanks.

**Comment by posva** [comment]
https://github.com/posva/unplugin-vue-router/issues/78#issuecomment-1277233360 😅
You are meant to implement it by yourself.

**Comment by jd-solanki** [comment]
oh, Sorry that was me again 😅 

Actually, I came back to `unplugin-vue-router` after long time.

**Comment by chojnicki** [comment]
@jd-solanki did you managed to get same naming convention as in nuxt or vite-plugin-pages? Did you wrote own function for that or some copy-paste approach was possible?

**Comment by jd-solanki** [comment]
@chojnicki Yes, here's the config that aligns it with nuxt:
```ts
// File: vite.config.ts
	getRouteName: routeNode => {
	  // Convert pascal case to kebab case
	  return getPascalCaseRouteName(routeNode)
	    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
	    .toLowerCase()
	},
```

**Comment by chojnicki** [comment]
@jd-solanki Works great, thanks.
