### ISSUE TITLE
sub folder layout render incorrect

### ISSUE THREAD

**Issue by bobby169** [posva/unplugin-vue-router#190]
I use `unplugin-vue-router` to test [Vitesse starter](https://github.com/antfu/vitesse/blob/main/src/main.ts). replace `pages` sub folder `pages->hi->[name].vue`
```html
<route lang="yaml">
meta:
  layout: home // replace other layout
</route>
```

the `[name].vue` not render the Corrected layout

**Comment by posva** [comment]
See https://github.com/posva/unplugin-vue-router/issues/29#issuecomment-1263298839
