### ISSUE TITLE
type ignoring folder with bracket

### ISSUE THREAD

**Issue by zynth17** [posva/unplugin-vue-router#20]
so i have a dynamic route on a folder name `[path]` is a folder and not a vue file. using `useRoute` with the route name does not infering the route type, it is ignoring the path if it is a folder

here is the code.
![image](https://user-images.githubusercontent.com/45350572/177369650-08927fbc-118c-46d7-9583-99405715119a.png)

here is how the folder structure
![image](https://user-images.githubusercontent.com/45350572/177370154-593a52d8-6ea1-4cad-93e1-489e6fe12d47.png)

**Comment by posva** [comment]
You are forcing the type of `route` but you shouldn't do that. Let `useRoute('routeName')` give you the name. I tried and it works.

Note that if you only have a folder `[path]`, it won't create a name for the route unless there is a `[path].vue` file alongside it (like with Nuxt).

**Comment by zynth17** [comment]
> You are forcing the type of `route` but you shouldn't do that. Let `useRoute('routeName')` give you the name. I tried and it works.

sorry i dont get what you mean with im forcing the type of route. 

> Note that if you only have a folder `[path]`, it won't create a name for the route unless there is a `[path].vue` file alongside it (like with Nuxt).

im naming the detail.vue file name not the [path] folder name? am i missing something here?

**Comment by posva** [comment]
~~Remove the `: RouteLocation`~~ Ah, that's just visual.

This works when I tested. Can you reproduce it in the repository?

**Comment by zynth17** [comment]
> ~Remove the `: RouteLocation`~ Ah, that's just visual.
> 
> This works when I tested. Can you reproduce it in the repository?

here the repro
https://github.com/zynth17/unplugin-vue-router-bug-dynamic-path

**Comment by posva** [comment]
Thanks, now I see the bug!

**Comment by zynth17** [comment]
> Thanks, now I see the bug!

no problem!
