### ISSUE TITLE
Data loaders: Invalid value used as weak map

### ISSUE THREAD

**Issue by minht11** [posva/unplugin-vue-router#206]
I don't have reporduction for this one, but it seems when using nested loaders, and very short cache time or when cache expires this code...
https://github.com/posva/unplugin-vue-router/blob/53ccfa5365f6c94f2928a1811f7f5353612027ba/src/data-fetching/defineLoader.ts#L201-L204
crashes with `Invalid value used as weak map`

**Comment by posva** [comment]
Unfortunately I can't really check with that information...
The loader part is being rewritten to have different versions with and without cache and the new version doesn't use a weak map anyway
