### ISSUE TITLE
Custom route block meta not working with beforeEach

### ISSUE THREAD

**Issue by veryard** [posva/unplugin-vue-router#21]
Hey,

Maybe I am doing something incorrectly but when I try to access a routes meta from the custom route block on `router.beforeEach` the meta is empty.

StackBlitz Example:
https://stackblitz.com/edit/vitejs-vite-w4wcwn?file=src%2Fmain.ts

Thanks.

**Comment by posva** [comment]
It wasn't yet implemented, it's now added and released 👍

**Comment by rbaprado** [comment]
I am currently having the exact same problem
