### ISSUE TITLE
About import 'vue-router/auto'

### ISSUE THREAD

**Issue by leessmin** [posva/unplugin-vue-router#212]
![Screenshot_20230808_173050](https://github.com/posva/unplugin-vue-router/assets/101449039/9c6664f5-df32-4490-9588-f4ebe85a351e)
Excuse me,What is the case,It reports an error, but the project starts normally,Causing me to have to use//@ ts ignore to avoid errors,

**Comment by posva** [comment]
See https://github.com/posva/unplugin-vue-router#typescript

**Comment by leessmin** [comment]
I also have a question as to why my nested routes are presented in batches instead of parent-child relationships

It wasn't under users when I visited www

**Comment by cesswhite** [comment]
@posva I have the same error when I run `npm run dev` command

![Captura de Pantalla 2023-08-15 a la(s) 14 36 43](https://github.com/posva/unplugin-vue-router/assets/44076866/53a731a7-2d1e-456b-be96-bdb3ba8ff598)


This is the repo to reproduce
https://github.com/cesswhite/buzzword-template-vue3.git

**Comment by angelhdzmultimedia** [comment]
I solved this by adding `typed-router.d.ts` in the `includes` array of `tsconfig.app.json` instead of `tsconfig.json`.
Clueless about why doesn't work in `tsconfig.json`.
