### ISSUE TITLE
Playground Sandbox

### ISSUE THREAD

**Issue by FlorianDevPhynix** [posva/unplugin-vue-router#213]
I'm a React/Solid.js not a vue developer, but I'm currently looking into routing library's and the typesafety of this library looks very interesting.
I wanted to see it in action so I created a Sandbox on Stackblitz. Maybe it could be included in the Readme, so people don't have to clone the whole repository to use the playground.
Sadly it's not possible to install vue plugins for VSCode in Stackblitz, so there's no editor support for typescript in vue.

https://stackblitz.com/edit/unplugin-vue-router-vite-playground

https://stackblitz.com/edit/unplugin-vue-router-vite-playground?file=src%2FApp.vue

**Comment by posva** [comment]
I'm glad you find it interesting! Maybe this pattern is used in the future for other frameworks 🤞 

Thanks for the stackblitz, I should indeed add an online demo to the readme even if the autocompletion doesn't show up on the vue files

**Comment by FlorianDevPhynix** [comment]
I'm definitely going to take some inspiration from this, for the extension of [vite-plugin-pages](https://github.com/hannoeru/vite-plugin-pages) that I'm working on right now. Typesafety for routing is one of the best use cases of typescript that I have seen.
