### ISSUE TITLE
Generate typed-router.d.ts in a specific generated folder

### ISSUE THREAD

**Issue by dest1n1s** [posva/unplugin-vue-router#219]
Currently `typed-router.d.ts` is generated directly in the root directory, which might not be elegant for a generated typing file that should be added to `.gitignore`. Some other frameworks choose to create directory like `.nuxt` and `.svelte-kit` to place generated files. Maybe `unplugin-vue-router` can similarly put the typings in location such as `.router/typed-router.d.ts` as the default behavior.

**Comment by posva** [comment]
This is already doable with the `dts` option. I prefer to keep the default generation at the root to be visible and let people decide where they want to put it.
