### ISSUE TITLE
The types for custom routes are not being generated.

### ISSUE THREAD

**Issue by alokVishu** [posva/unplugin-vue-router#222]
Hello,

I am using some custom routes. Like below:

```ts
 {
    path: '/apps/email/:filter',
    name: 'apps-email-filter',
    component: emailRouteComponent,
  },

  // Email label
  {
    path: '/apps/email/label/:label',
    name: 'apps-email-label',
    component: emailRouteComponent,
  },
```

So it gets below errors:
![image](https://github.com/posva/unplugin-vue-router/assets/80033712/f8625448-1d66-4674-a01b-f629cb24337c)

What should I do to resolve it?

**Comment by posva** [comment]
This is normal for `extendRoutes()` as it's a runtime option. You can use build time options instead: https://github.com/posva/unplugin-vue-router/blob/main/src/options.ts#L111
