### ISSUE TITLE
route blocks should be stripped in client code

### ISSUE THREAD

**Issue by zynth17** [posva/unplugin-vue-router#23]
so, i'm trying to migrate once more. 
but now it raise a new problem. i have no idea where is this came from.

this the error on browser log
![image](https://user-images.githubusercontent.com/45350572/177507004-cb895f77-254f-49b5-9e36-28be1770022c.png)

the new red error is showing the error in this source map, but there is nothing wrong with the custom route block on my file.
![image](https://user-images.githubusercontent.com/45350572/177507362-20f5a3af-2b58-47b8-a811-c4f33c1d5320.png)

**Comment by posva** [comment]
So weird. This one I don't see where it comes from, I couldn't reproduce locally. Let me know if you manage to reproduce so I can check.

**Comment by zynth17** [comment]
> So weird. This one I don't see where it comes from, I couldn't reproduce locally. Let me know if you manage to reproduce so I can check.

sure, i also still finding a way to reproduce this one

**Comment by zynth17** [comment]
> I see. I think the problem comes from using yaml. I need to figure out why, but if you use json instead, it won't fail. There is a request that shouldn't be happenning

the problem with my file is i'm using json and this error still happening, will try again tomorrow, might be caching problem.

**Comment by zynth17** [comment]
just tried once again and it is still does not work even with `lang="json"`

**Comment by posva** [comment]
hmm, then it's coming from somewhere else but I can't figure out why. On the reproduction the problem disappears when using json and the error seems to come from the router dynamic import of the route trying to parse yaml as js, so I'm really surprised using json doesn't suppress the error for you.

**Comment by zynth17** [comment]
> hmm, then it's coming from somewhere else but I can't figure out why. On the reproduction the problem disappears when using json and the error seems to come from the router dynamic import of the route trying to parse yaml as js, so I'm really surprised using json doesn't suppress the error for you.

are you able to fix the yaml one? i will try once again after you fix that one and change my route block to yaml and see if it will work

**Comment by hannoeru** [comment]
This is how I resolve this problem in vite-plugin-pages:
Just resolve all custom block as virtual module and load it with a empty export like this https://github.com/hannoeru/vite-plugin-pages/blob/fab215b79db7d2e1d93b08981ca31ced2718f4f1/src/index.ts#L59-L64

**Comment by posva** [comment]
Thanks, @hannoeru, I was about to ping you here 😆
