### ISSUE TITLE
Routes not showing up in devtools

### ISSUE THREAD

**Issue by dasmikko** [posva/unplugin-vue-router#235]
I just switched from vite-plugin-pages to this, now my routes don't show up in the devtools?

I'm not sure if this is a bug with the plugin or the devtools.

This is my folder structure:
![image](https://github.com/posva/unplugin-vue-router/assets/4254869/9d94b089-06e8-4ed9-a26e-573b3053d877)

This is the route object generated:
![image](https://github.com/posva/unplugin-vue-router/assets/4254869/c3c21421-b78c-4293-96bb-66b11ef9fc7b)

This is what shows up in vue devtools:
![image](https://github.com/posva/unplugin-vue-router/assets/4254869/3be57efa-2e02-4c80-9f6f-89d0c071364b)

**Comment by posva** [comment]
It works when I test locally 👀

![Screenshot 2023-09-22 at 08 52 45](https://github.com/posva/unplugin-vue-router/assets/664177/73bd91b8-2bb3-440c-9865-1e867fd03eac)

Have you tried closing and reopening devtools? they sometimes get out of sync.

**Comment by dasmikko** [comment]
I have. Still the same issue.

I have even tried deleting node_modules and reinstalling everything. No change. I'm very confused. 

I even went as far to test in firefox, but same result.

**Comment by posva** [comment]
Turns out it was a vue-router bug
