### ISSUE TITLE
Bug?: routesfolder path function must return value ending with `.vue`

### ISSUE THREAD

**Issue by PindaPixel** [posva/unplugin-vue-router#256]
It was a bit of a head scratcher for me when trying to implement a custom mapping for URLs. 
Using the following configration:

```ts
routesFolder: [
    {
        src: "src/modules",
        path: (filePath) => {
            return filePath
                .slice(filePath.indexOf("src/modules") + "src/modules".length)
                .replace("pages/", "")
                .replace("-page.vue", "")
        },
        extensions: ["-page.vue"],
    },
],
```
It defined the routes but did not bind any components to it.
Instead, I had to use `replace("-page", "")`, leaving the .vue extension to get the desired behaviour.

It feels a bit odd, because in my mind I'm supposed to return just a URL. Is this by design?

**Comment by posva** [comment]
Yes, this is intended, I think it’s already documented in the option. It’s probably just bad naming though

**Comment by PindaPixel** [comment]
Alright, thanks for clarifying
