### ISSUE TITLE
Usage with unplugin-vue-components

### ISSUE THREAD

**Issue by valgeirb** [posva/unplugin-vue-router#26]
Is it possible to get [unplugin-vue-components](https://github.com/antfu/unplugin-vue-components) to work with this plugin?

Currently the `components.d.ts` file that unplugin-vue-components generates uses components from `vue-router` (should be from `@vue-router` I think?):

```js
RouterLink: typeof import('vue-router')['RouterLink']
RouterView: typeof import('vue-router')['RouterView']
```

I believe this is what's causing build errors with TS like: 

```
Property 'isActive' does not exist on type 'RouteLocationResolvedTyped<RouteNamedMap, "/"> | RouteLocationResolvedTyped<RouteNamedMap, "/[...all]"> | ... 16 more ... | RouteLocationResolvedTyped<...>'.

11   <RouterLink :to="to" v-slot="{ isActive }">
```

because I can get rid of these errors by manually importing the RouterLink component from `@vue-router` as an example.

**Comment by posva** [comment]
You can simply remove that preset because the plugin register global components anyway so you **shouldn't** import any router component directly and everything will just work.
