### ISSUE TITLE
Does this work in build too?

### ISSUE THREAD

**Issue by jossephus** [posva/unplugin-vue-router#263]
According to this https://github.com/posva/unplugin-vue-router/issues/2/ it says it works in build too but refreshing on pages does not work correctly in build.

Reproduction: https://stackblitz.com/github/jossephus/vue-router-build-test

Steps to reproduce:
1. build the project: pnpm build
2. Open the built project from dist.. Routing works fine... we can go to other pages and go back... but refreshing when the url path is not "/" gives cannot get url error: shown below

![image](https://github.com/posva/unplugin-vue-router/assets/46337696/0047ba98-30e9-4065-b31b-e0cdd89bf4c4)

**Comment by posva** [comment]
That’s because you’re not serving the folder just opening the file. It’s not related to the plugin
