### ISSUE TITLE
RouterLink v-slot props missing types

### ISSUE THREAD

**Issue by valgeirb** [posva/unplugin-vue-router#27]
We're missing some types for `route`, `navigate`,`isActive` and `isExactActive` slot props.

```
Property 'route' does not exist on type 'RouteLocationResolvedTyped<RouteNamedMap, "/AboutView"> | RouteLocationResolvedTyped<RouteNamedMap, "/HomeView">'.

23           v-slot="{ href, route, navigate, isActive, isExactActive }"
```

![image](https://user-images.githubusercontent.com/2593027/177634111-a52ef8e3-9438-4b5c-9c60-dbfdd9b6232e.png)

I have a reproduction repo ready if you need it.

**Comment by posva** [comment]
Thanks! No need for the repro, I found where this is coming from
