### ISSUE TITLE
not working with vite-plugin-vue-layouts

### ISSUE THREAD

**Issue by hi-reeve** [posva/unplugin-vue-router#29]
the problem with route block on #23 is resolved.
however [5d3c040](https://github.com/posva/unplugin-vue-router/commit/5d3c0402a8feb847b09cbfa2b13fd26ecf663733) make the vite-plugin-vue-layouts does not work, its ignoring the layout and just showing the page content.

screenshot, supposed to have sidebar and navbar but now only showing the content.
![image](https://user-images.githubusercontent.com/45350572/177756134-6616035c-4ea4-41a6-9d29-0dc15fe839fa.png)

**Comment by posva** [comment]
can you provide a repro for this one? 

Have you tried changing the order of the plugins in the vite config? Maybe I shouldn't add the `enforce: 'pre'` to this plugin

**Comment by zynth17** [comment]
> can you provide a repro for this one?

updated the repro to the latest version [repro](https://github.com/zynth17/unplugin-vue-router-bug-dynamic-path).


> Have you tried changing the order of the plugins in the vite config? Maybe I shouldn't add the `enforce: 'pre'` to this plugin

yes, and it still does not work.

**Comment by posva** [comment]
So I checked a bit further and this seems to be a bug on the plugin not applying layouts to nested routes

**Comment by zynth17** [comment]
> It turns out you were missing the wrapping `meta`:
> 
> ```json
> {
>   "name": "other",
>   "meta": {
>     "layout": "other"
>   }
> }
> ```
> 
> Also, note `setupLayouts()` returns a copy, so you cannot just call the method on routes.
> 
> The whole fixed example is at [zynth17/unplugin-vue-router-bug-dynamic-path#1](https://github.com/zynth17/unplugin-vue-router-bug-dynamic-path/pull/1)

ah right i missing that one on the bug repro, but it still does not work on my real project 😂
i will find a way to reproduce the bug

**Comment by posva** [comment]
They only support layouts in root-level routes (https://github.com/posva/unplugin-vue-router/issues/29#issuecomment-1177571991) it could be that

**Comment by lrstanley** [comment]
Ran into some of the similar issues, due to how unplugin-vue-router uses `children` whereas I don't believe vite-plugin-pages does -- I believe it flattens everything (and thus I never ran into the issue of children not supporting layouts via that plugin).

Wrote something quick and dirty that will recursively initialize layouts utilizing `extendRoutes`.

```typescript
// file: src/lib/core/router.ts

import { setupLayouts } from "virtual:generated-layouts"
import { createRouter, createWebHistory } from "vue-router/auto"
import type { RouteRecordRaw } from "vue-router/auto"

function recursiveLayouts(route: RouteRecordRaw): RouteRecordRaw {
  if (route.children) {
    for (let i = 0; i < route.children.length; i++) {
      route.children[i] = recursiveLayouts(route.children[i])
    }

    return route
  }

  return setupLayouts([route])[0]
}

const router = createRouter({
  history: createWebHistory("/"),
  extendRoutes(routes) {
    return routes.map((route) => {
      // My custom extendRoutes logic, that adds a meta field to force specific pages under
      // a given path to require auth.
      if (route.path.startsWith("/admin") || route.path.startsWith("/dashboard")) {
        route = {
          ...route,
          meta: {
            auth: true,
            ...route.meta,
          },
        }
      }

      // For each route, pass it to recursiveLayouts, which will apply layouts properly
      // (without duplicating or accidentally double-wrapping components).
      return recursiveLayouts(route)
    })
  },
})
```

Suspect this will be useful for others as well. Though I'm curious @posva, if it makes more sense to use a flat layout for the generated route structure, similar to what I think vite-plugin-pages does? (as a `children` approach technically isn't required iirc) -- are there any downsides with that approach?

**Comment by posva** [comment]
> if it makes more sense to use a flat layout for the generated route structure, similar to what I think vite-plugin-pages does?

It's just more convenient and it's something we support in vue router (omitting the `component` with `children`) to allow nesting paths without nesting layouts. It also generates a more structured routing structure this way.

Note you can unnest routes: `dashboard/admin.vue` -> `dashboard.admin.vue` but I think, ultimately, vite-plugin-vue-layouts should apply recursively to children when there isn't a `component` option as this is a syntax [we intentionally added to vue-router](https://github.com/vuejs/router/issues/1174) and it would be nice if that vite plugins supports it too

**Comment by lrstanley** [comment]
I've made a feature request for vite-plugin-vue-layouts [here](https://github.com/JohnCampionJr/vite-plugin-vue-layouts/issues/78), though, while making that request, I noticed that there might be something unplugin-vue-router is doing that will make it more complex to properly implement in the layouts package. As shown in the linked issue, this is a subset of one of the root/parent routes I have:

```typescript
{
    "path": "/info",
    "children": [
        {
            "path": "privacy",
            "component": {/* ... */}, /* <--- why is the component here */
            "children": [
                {
                    "path": "",
                    "name": "/info/privacy", /* <--- and not here? */
                    "meta": {
                        "title": "Privacy Policy"
                    }
                }
            ]
        },
        {
            "path": "service-health",
            "component": {/* ... */},
            "children": [
                {
                    "path": "",
                    "name": "/info/service-health",
                    "meta": {
                        "title": "Service Health"
                    }
                }
            ]
        },
        {
            "path": "terms",
            "component": {/* ... */},
            "children": [
                {
                    "path": "",
                    "name": "/info/terms",
                    "meta": {
                        "title": "Terms of Service"
                    }
                }
            ]
        }
    ]
}
```

I added it into the above examples comments, but I'm noticing the component is being bound to a route, and the actual meta information is being put into the child of that route. I'd imagine for the layouts package to work correctly, the meta fields would need to be on the same level as the actual component.

Something like one of the two examples:

```typescript
{
    "path": "/info",
    "children": [
        {
            "path": "privacy",
            "children": [
                {
                    "path": "",
                    "name": "/info/privacy",
                    "component": { /* ... */},
                    "meta": {
                        "title": "Privacy Policy"
                    }
                }
            ]
        },
        {
            "path": "service-health",
            "children": [
                {
                    "path": "",
                    "name": "/info/service-health",
                    "component": { /* ... */},
                    "meta": {
                        "title": "Service Health"
                    }
                }
            ]
        },
        {
            "path": "terms",
            "children": [
                {
                    "path": "",
                    "name": "/info/terms",
                    "component": { /* ... */},
                    "meta": {
                        "title": "Terms of Service"
                    }
                }
            ]
        }
    ]
}
```

or:

```typescript
{
    "path": "/info",
    "children": [
        {
            "path": "privacy",
            "component": { /* ... */},
            "name": "/info/privacy",
            "meta": {
                "title": "Privacy Policy"
            }
        },
        {
            "path": "service-health",
            "component": { /* ... */},
            "name": "/info/service-health",
            "meta": {
                "title": "Service Health"
            }
        },
        {
            "path": "terms",
            "component": { /* ... */},
            "name": "/info/terms",
            "meta": {
                "title": "Terms of Service"
            }
        }
    ]
}
```

I imagine the recursive logic for adding routes would be something like `if (route.children && !route.component)` to recurse, and only looking to add a route when `if (route.component && route.meta.layout)` however the latter wouldn't work, as the meta fields are disjointed from the actual component.

**Comment by posva** [comment]
What is the file tree that generates those routes? This plugin shouldn’t generate empty route children like that, they are not valid for vue router

**Comment by lrstanley** [comment]
It looks like it's actually due to the layouts plugin. I printed at the start of `extendRoutes` with the expectation that it was before those were actually modified by any logic, however it looks like `console.log` was being executed after it passed through the layouts plugin, which add that additional structure in the routing tree.

Feel free to ignore.
