### ISSUE TITLE
 Combining with electron will cause `RouterView` to not render correctly

### ISSUE THREAD

**Issue by awdr74100** [posva/unplugin-vue-router#316]
Reproduction: https://github.com/awdr74100/unplugin-vue-router-bug-reproduction

Run the following command:

```sh
pnpm i && pnpm dev
```

Everything works fine, but: 

```sh
pnpm build:electron
```

`RouterView` seems to need to be manually switched to load correctly, which is different from the automatic loading behavior of the `index.vue` presented by `pnpm dev`.

The original vue-router does not have this unexpected behavior.

It seems that the key to the problem is that `RouterView` is not loaded correctly in `index.vue`.

**Comment by posva** [comment]
I don't think this is related to the plugin. You don't need (and shouldn't) to import RouterView and RouterLink https://github.com/awdr74100/unplugin-vue-router-bug-reproduction/blob/master/src/App.vue#L2

**Comment by awdr74100** [comment]
Sorry about this, try changing `createWebHistory` to `createWebHashHistory` in electron and it will work fine.

**Comment by mrmmg** [comment]
> Sorry about this, try changing `createWebHistory` to `createWebHashHistory` in electron and it will work fine.

You saved my time and life bro! Thanks You A Lot,

**Comment by posva** [comment]
You probably want `createMemoryHistory()` if you don't have a URL BTW. It all depends on what's the URL like. web history doesn't work with `file://` but hash does
