### ISSUE TITLE
TS2742 The inferred type of … cannot be named without a reference to …

### ISSUE THREAD

**Issue by awdr74100** [posva/unplugin-vue-router#322]
repo: https://github.com/awdr74100/unplugin-vue-router-bug-reproduction

<img width="1351" alt="截圖 2024-02-22 晚上11 13 41" src="https://github.com/posva/unplugin-vue-router/assets/47501692/4b37c0b8-e53e-40aa-91e3-593899166091">

```txt
src/router/index.ts:3:7 - error TS2742: The inferred type of 'router' cannot be named without a reference to '../../node_modules/unplugin-vue-router/dist/router-C96Op3uj.mjs'. This is likely not portable. A type annotation is necessary.
```

This seems to be a type error, and no error will occur in actual operation.

Thank you for your immediate help every time!

**Comment by posva** [comment]
As a workaround add `import { type _RouterTyped } from 'unplugin-vue-router/types'` to the top of the file
