### ISSUE TITLE
error on refresh if path contain symbol or encoded uri

### ISSUE THREAD

**Issue by zynth17** [posva/unplugin-vue-router#34]
if we had dynamic path containing symbol e.g `user/test@test.com` , this cause an error when we refreshing the page, it has no problem on the first redirect using spa.

repro
[bug](https://github.com/zynth17/unplugin-vue-router-bug-dynamic-path)

**Comment by zynth17** [comment]
> This seems to be a vite bug as accessing the page directly doesn't go through this plugin nor vue router. You should open an issue there.

it has no problem with vite-plugin-pages. i will try to open issue on vite then.

**Comment by posva** [comment]
Hmm, it’s weird. I will have to give it a second look later

**Comment by zynth17** [comment]
> Hmm, it’s weird. I will have to give it a second look later 

sure but i does seems like vite problem since the error on running --debug with vite showing that it wont redirect because the path contain dot.

you can check the detail on https://github.com/vitejs/vite/issues/9135
