### ISSUE TITLE
 TypeScript Errors Caused by vitest Configuration in Vue App Build

### ISSUE THREAD

**Issue by MooseSaeed** [posva/unplugin-vue-router#353]
### Issue Description:

Encountering TypeScript errors related to the `vue-router/auto` when building a fresh Vue 3 application created with `npm create vue@latest`. The errors occur specifically with the `createRouter` and `createWebHistory` functions.

### Steps to Reproduce:

1. Create a fresh Vue app using `npm create vue@latest` with the below configuration.

<img width="523" alt="Screenshot 2024-03-27 at 8 18 59 PM" src="https://github.com/posva/unplugin-vue-router/assets/94674993/6ddc39d4-4ba3-440e-a04a-1b5be2c49a4d">

2. Install and configure `unplugin-vue-router`.
3. Run npm run build.
4. Observe the TypeScript errors in the terminal.

### Expected Behavior:

The Vue application should build successfully without any TypeScript errors related to the `vue-router/auto`.

### Actual Behavior:

Encountering TypeScript errors

```bash
src/router/index.ts:1:10 - error TS2305: Module '"vue-router/auto"' has no exported member 'createRouter'.

1 import { createRouter, createWebHistory } from 'vue-router/auto'
           ~~~~~~~~~~~~

src/router/index.ts:1:24 - error TS2305: Module '"vue-router/auto"' has no exported member 'createWebHistory'.

1 import { createRouter, createWebHistory } from 'vue-router/auto'
                         ~~~~~~~~~~~~~~~~
```

### Additional Context:

The errors are resolved by removing the path configuration for Vitest from `tsconfig.json`, which was added automatically during the creation of the Vue app.

```json
    {
      "path": "./tsconfig.vitest.json"
    }
```

### Reproduction Repository:

A reproduction of the issue has been created at: [MooseSaeed/tsc-error](https://github.com/MooseSaeed/tsc-error)

**Comment by posva** [comment]
I’m interested in the resolution of this config issue to add it to docs but it doesn’t seem to be about the code, just a config issue

**Comment by MartinX3** [comment]
I can confirm this issue with Quasar (based on vue3).

**Comment by 94726** [comment]
I was able to make the `npm create vue@latest` work by adding
`/// <reference types="unplugin-vue-router/client" />` to env.d.ts instead of using the `compilerOptions.types` inside tsconfig
e.g.
```ts
/// <reference types="vite/client" />
/// <reference types="unplugin-vue-router/client" />
```

**Comment by alokVishu** [comment]
I'm experiencing the same issue in Vue.js and Vite projects. Has anyone found a solution?

**Comment by jonaaldas** [comment]
Does anybody have a solution for this? I am still having problems and the solutions listed do not work.

**Comment by ultimateshadsform** [comment]
For some reason this has stopped working and is generating errors but works fine in browser:

![image](https://github.com/posva/unplugin-vue-router/assets/151234273/d6b65df6-b16f-4723-b144-3b91766422f6)

![image](https://github.com/posva/unplugin-vue-router/assets/151234273/401bc2d0-745e-4ba2-ad07-820182065788)

It doesn't generate needed types for some reason.

**Comment by a0s** [comment]
@posva Hi! I am not sure this is related , but with "unplugin-vue-router": "^0.8.7" i have 
```
computing gzip size (27)...src/router/index.ts:5:9 - error TS2305: Module '"vue-router/auto"' has no exported member 'createRouter'.

5 import {createRouter, createWebHistory} from 'vue-router/auto'
          ~~~~~~~~~~~~

src/router/index.ts:5:23 - error TS2305: Module '"vue-router/auto"' has no exported member 'createWebHistory'.

5 import {createRouter, createWebHistory} from 'vue-router/auto'
                        ~~~~~~~~~~~~~~~~

```
is this known bug/behaviour?

tsconfig.app.json:
```json
{
  "extends": "@vue/tsconfig/tsconfig.dom.json",
  "include": [
    "env.d.ts",
    "src/**/*",
    "src/**/*.vue",
    "./typed-router.d.ts"
  ],
  "exclude": [
    "src/**/__tests__/*"
  ],
  "compilerOptions": {
    "strict": true,
    "composite": true,
    "tsBuildInfoFile": "./node_modules/.tmp/tsconfig.app.tsbuildinfo",
    "baseUrl": ".",
    "paths": {
      "@/*": [
        "./src/*"
      ]
    },
    "types": [
      "unplugin-vue-router/client"
    ]
  }
}
```
