### ISSUE TITLE
Custom block 'route' is not highlighted

### ISSUE THREAD

**Issue by xcchcaptain** [posva/unplugin-vue-router#354]
i don't use Volar, used Vue-Official tool,
i don't know if it should be 'Vue-Official'  to support it.
![image](https://github.com/posva/unplugin-vue-router/assets/5080022/c5f20acc-5745-4d1d-801f-434d174de143)

**Comment by posva** [comment]
FYI volar is the official tool. And yes, it’s the extension that handles it
