### ISSUE TITLE
Support to sort routes by custom comparator

### ISSUE THREAD

**Issue by carrypann** [posva/unplugin-vue-router#391]
I am looking for a way to get sorted routes (for auto generate nav menus), and I find a method [getSortedChildren](https://github.com/posva/unplugin-vue-router/blob/8b3e1f028c521d7a3f1e4b068411e4a0a0f38577/src/core/tree.ts#L150) which use `path` variable to compare, is there any way to get sort routes by custom comparator(e.g using `meta.sort`)

**Comment by posva** [comment]
Yeah, you can write that function yourself with router.getRoutes(). BTW here, routes are in a tree
