### ISSUE TITLE
Invalid route path generated when trying to use `/pages/index.vue` as layout

### ISSUE THREAD

**Issue by MellKam** [posva/unplugin-vue-router#442]
Hi! I want to create the layout for my dashboard, but I don't want to set path for it [as in docs](https://uvr.esm.is/guide/file-based-routing.html#nested-routes). I want it to start from root `/`. I came up with the following strucutre:

```
/src/pages/index.vue (layout)
/src/pages/index/servers/index.vue (alias to `/`, so it can be accessed as main page)
/src/pages/index/users/index.vue 
```

I also have other pages that dont need this layout, so I can't just move it all to `App.vue`

```
/src/pages/login/index.vue (doesn't need index layout)
```

Here is how it looks in code: https://stackblitz.com/edit/github-wfreqt-udvslk?file=typed-router.d.ts

Everything seems to be working just fine, but generated types are not exactly correct. For some reason another slash is inserted for pages with index layout
![image](https://github.com/user-attachments/assets/a595398c-5cd5-497e-afa7-0b58b810a2b2)

I would like to know if there's a better way to structure this. Thanks for your work, awsome library ❤️

**Comment by posva** [comment]
Thanks, I'm glad you like it!

They type isn't wrong, that's the name given to the route. If you use it, it works. You can customize how names are set with getRouteName (https://uvr.esm.is/guide/configuration.html)
