### ISSUE TITLE
useRoute().params is not giving the proper types after v0.10.1

### ISSUE THREAD

**Issue by MooseSaeed** [posva/unplugin-vue-router#459]
## Issue Summary:

The `useRoute().params` is no longer returning the proper types for its properties. I'm getting the error in the below screenshot after updating to the latest version (v0.10.1)

<img width="1803" alt="Screenshot 2024-07-30 at 4 37 18 PM" src="https://github.com/user-attachments/assets/9f05203b-b631-4ff2-83a8-09264612fa4e">

## Expected Behavior:
Previously, the `useRoute().params` type was `(property) RouteLocationNormalizedGeneric.params: RouteParamsGeneric`:

<img width="1753" alt="Screenshot 2024-07-30 at 4 43 08 PM" src="https://github.com/user-attachments/assets/4b05aff3-d1a0-41e7-85f3-d82b8a0303c9">

Any of its properties used to be a type of `string | string[]`.

## Current Behavior: 

Currently, with version 0.10.1, it returns the below:

<img width="1795" alt="Screenshot 2024-07-30 at 4 47 41 PM" src="https://github.com/user-attachments/assets/eec7e15a-516d-483a-a456-869359cfb03f">

And trying to access any of its properties returns the error in the first screenshot:

```
Property 'slug' does not exist on type 'Record<never, never> | { slug: string; }'.
  Property 'slug' does not exist on type 'Record<never, never>'.ts-plugin(2339)
any
```

Same issue is happening if used `$route` instead.

## Reproduction:

Here's a simple repro: https://github.com/MooseSaeed/unplugin-auto-router-issue-repro

**Comment by posva** [comment]
This is actually the expected behavior: it's a stricter version of the available types. Use `useRoute('/[slug]')` if you want to narrow down the type

**Comment by posva** [comment]
Yes, in the docs.
I wished it was like that too but that would require developing and running a typescript language server plugin and facing a whole new set of troubles through maintaining and upgrading. Passing the parameter is a much more maintainable solution
