### ISSUE TITLE
Can I disable route level code-splitting

### ISSUE THREAD

**Issue by web2033** [posva/unplugin-vue-router#47]
to get one js chunk in dist?

**Comment by posva** [comment]
It cannot be disabled yet.

**Comment by web2033** [comment]
Specifying `VueRouter({ importMode: 'sync' }),` or `VueRouter({ importMode: 'async' }),`
breaks both dev/build with vite, but works when omitting: `VueRouter({}),`

**Comment by web2033** [comment]
0.2.0

**Comment by web2033** [comment]
Works in 0.2.1
Thanks.
