### ISSUE TITLE
Passing Props to Route Components

### ISSUE THREAD

**Issue by heartbeatLV** [posva/unplugin-vue-router#49]
great plugin 🎊 

is there a way to pass `props: true` to the route definition?

[docs](https://router.vuejs.org/guide/essentials/passing-props.html)

[stackblitz](https://stackblitz.com/edit/vitejs-vite-k932qr?file=src%2Fpages%2Fusers%2F[id].vue)

[vite plugin pages](https://github.com/hannoeru/vite-plugin-pages#dynamic-routes)

**Comment by posva** [comment]
it should be passed with the route block
