### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'forEach')

### ISSUE THREAD

**Issue by charismafight** [posva/unplugin-vue-router#496]
Hi there,
I created a new vue project by 'vue create' to test this package, followed the installation and migrating part, I've got 'Uncaught TypeError: Cannot read properties of undefined (reading 'forEach')' error from router.ts. I found out that routes imported from 'vue-router/auto-routes' is undefined. And I have also created another project using vite, and it worked correctly. The only difference is the vite.config.ts and vue.config.js. Anybody can help me solving this problem? Thanks.

> vue.config.js
```javascript
module.exports = {
  configureWebpack: {
    resolve: { extensions: [".ts", ".tsx", ".js", ".json"] },
    plugins: [
      require('unplugin-vue-router/webpack')({
        /* options */
      }),
    ],
    module: {
      rules: [
        {
          test: /\.tsx?$/,
          loader: 'ts-loader',
          exclude: /node_modules/,
          options: {
            appendTsSuffixTo: [/\.vue$/],
          }
        }
      ]
    }
  },
}
```

> tsconfig.json
```json
{
  "include": [
    // other files...
    "./typed-router.d.ts"
  ],
  "compilerOptions": {
    "moduleResolution": "Bundler",
    "target": "es2016",
    "module": "commonjs", /* Specify what module code is generated. */
    "types": [
      "unplugin-vue-router/client"
    ],
    "esModuleInterop": true, /* Emit additional JavaScript to ease support for importing CommonJS modules. This enables 'allowSyntheticDefaultImports' for type compatibility. */
    "forceConsistentCasingInFileNames": true, /* Ensure that casing is correct in imports. */
    "strict": true, /* Enable all strict type-checking options. */
    "skipLibCheck": true /* Skip type checking all .d.ts files. */
  }
}
```

> typed-router.d.ts

```typescript
/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
  }
}

```

>tsconfig.json
```json
{
  "include": [
    // other files...
    "./typed-router.d.ts"
  ],
  "compilerOptions": {
    "moduleResolution": "Bundler",
    "target": "es2016",
    "module": "commonjs", /* Specify what module code is generated. */
    "types": [
      "unplugin-vue-router/client"
    ],
    "esModuleInterop": true, /* Emit additional JavaScript to ease support for importing CommonJS modules. This enables 'allowSyntheticDefaultImports' for type compatibility. */
    "forceConsistentCasingInFileNames": true, /* Ensure that casing is correct in imports. */
    "strict": true, /* Enable all strict type-checking options. */
    "skipLibCheck": true /* Skip type checking all .d.ts files. */
  }
}
```

>router.ts
```typescript
import { createRouter, createWebHistory } from 'vue-router'
import { routes } from 'vue-router/auto-routes'

export const router = createRouter({
    history: createWebHistory(),
    routes,
});
```

>main.js
```javascript
import { createApp } from 'vue'
import App from './App.vue'
import { router } from './router'

createApp(App)
    .use(router)
    .mount('#app')
```

**Comment by posva** [comment]
There are probably some updates needed for webpack. See #488 .
For the moment, use Vite. It's the recommended bundler for new projects too.

**Comment by charismafight** [comment]
npm list webpack showed 'webpack@5.94.0', I reinstalled it and still not worked, any further suggestion?
In fact, I want to migrate an exsiting project and keep the deployment config, so I create a new project with webpack just for test.

**Comment by zhangmo8** [comment]
> npm list webpack showed 'webpack@5.94.0', I reinstalled it and still not worked, any further suggestion?
> 
> In fact, I want to migrate an exsiting project and keep the deployment config, so I create a new project with webpack just for test.

Is it convenient to post a whole smallest project to help me understand and solve the error report?

**Comment by charismafight** [comment]
> > npm list webpack showed 'webpack@5.94.0', I reinstalled it and still not worked, any further suggestion?
> > In fact, I want to migrate an exsiting project and keep the deployment config, so I create a new project with webpack just for test.
> 
> Is it convenient to post a whole smallest project to help me understand and solve the error report?

@zhangmo8 Sure, thanks a lot. 
[vuerouter.zip](https://github.com/user-attachments/files/16851877/vuerouter.zip)

**Comment by zhangmo8** [comment]
> > > npm list webpack showed 'webpack@5.94.0', I reinstalled it and still not worked, any further suggestion?
> > > In fact, I want to migrate an exsiting project and keep the deployment config, so I create a new project with webpack just for test.
> > 
> > 
> > Is it convenient to post a whole smallest project to help me understand and solve the error report?
> 
> @zhangmo8 Sure, thanks a lot. [vuerouter.zip](https://github.com/user-attachments/files/16851877/vuerouter.zip)

It's working normally. Make sure eslint works when you give us the minimum demo @charismafight 
[vuerouter66.zip](https://github.com/user-attachments/files/16862211/vuerouter.zip)

**Comment by charismafight** [comment]
> It's working normally. 

That's weird, I've tried your version and it's still not worked. ( I just use npm intall and npm run serve)
![image](https://github.com/user-attachments/assets/abd7c22a-a1e4-46aa-8967-2e3ced6adf2b)

![image](https://github.com/user-attachments/assets/d21c1966-a5b2-4497-92a9-bbb8d29588e8)


> Make sure eslint works when you give us the minimum demo @charismafight 

Okay, I will note that.

**Comment by zhangmo8** [comment]
<img width="73" alt="image" src="https://github.com/user-attachments/assets/2c8e115c-0f58-4121-9464-b3a960825ca1">
What's your Node version and npm version
@charismafight

**Comment by charismafight** [comment]
@zhangmo8 
node   v20.13.1
npm    10.8.2

**Comment by zhangmo8** [comment]
It's strange that I can run normally in my local.

**Comment by zam157** [comment]
Are you on Windows? I have the same problem using rspack on Windows

**Comment by ElysiaEgo** [comment]
Same problem on Windows with rsbuild. Moving the project to Linux without changes and it works perfectly.

**Comment by Deuscx** [comment]
made a config in Windows which is useful for me 
```ts
  dev: {
    // windows unplugin-vue-router not support hmr, so reload server
    watchFiles: {
      type: 'reload-server',
      paths: ['./typed-router.d.ts'],
    },
  },
  tools: {
    async rspack(config) {
      const { scanPages, generateRoutes } = createRoutesContext(resolveOptions({ }))
      await scanPages()
      config.plugins?.push(new RspackVirtualModulePlugin({
        'vue-router/auto-routes': generateRoutes(),
      }))
```
 https://github.com/Deuscx/starter-rspack-vue/blob/main/rsbuild.config.ts#L21-L38
