### ISSUE TITLE
type safety query

### ISSUE THREAD

**Issue by hi-reeve** [posva/unplugin-vue-router#508]
hi, recently i just found out about this new [library](https://router.kitbag.dev/) for vue router.
this looks good with all the query define for query type safety, i think this is a good approach on how we can define a type safe query.
maybe we can include this in the `definePage` macro?

**Comment by posva** [comment]
There is actually a whole new matcher mechanism in Vue router that allows much more 😁
Stay tuned

**Comment by christopher-buku** [comment]
> There is actually a whole new matcher mechanism in Vue router that allows much more 😁. You can check some of router branches if you are curious Stay tuned

oh wow! will check it, thanks!

**Comment by NickDomanti** [comment]
> There is actually a whole new matcher mechanism in Vue router that allows much more 😁. You can check some of router branches if you are curious Stay tuned

Could you provide a link/guide or something? I really like unplugin-vue-router but I really want to have a typed query, it feels wrong not to.

**Comment by NickDomanti** [comment]
> It will be up as an experimental feature in [vuejs/router#2415](https://github.com/vuejs/router/pull/2415)

Is there a way I can get a notification or something when the feature is out?
Sorry I'm not that well versed with GitHub.

**Comment by posva** [comment]
"Subscribe" on the side
