### ISSUE TITLE
index.vue at the root level injects two slashes in the url for its nested child routes

### ISSUE THREAD

**Issue by Shujee** [posva/unplugin-vue-router#534]
I have my `index.vue` page at the root level, inside `pages` directory and some nested children of it inside the index sub-folder:

```
src/pages/
├── index.vue
└── index/
    ├── login@dialog.vue
    └── register@dialog.vue
```
This structure results in unwanted double slashes in the URLs of nested routes:

```
export interface RouteNamedMap {
    '': RouteRecordInfo<'', '/', Record<never, never>, Record<never, never>>,
    '//login': RouteRecordInfo<'//login', '/login', Record<never, never>, Record<never, never>>,
}
```
I can workaround the problem by adding a JSON block in the login component and define route name there, but just want to make sure I'm not doing anything wrong here, in case there is some better/standard approach for this VERY common scneario.

**Comment by posva** [comment]
That's the name. The URL has only one. This ensures unique names but you can customize it.
