### ISSUE TITLE
Handle TypeScript syntax within `definePage()`

### ISSUE THREAD

**Issue by posva** [posva/unplugin-vue-router#57]
Using TS syntax will produce Syntax errors:

```vue
<script setup>
definePage({
  alias: 'thing' as string,
})
</script>
```

Not sure how to support this but I think it should be related to adding `?vue&type...` query to import. TODO: check with the vite vue plugin

**Comment by undead-voron** [comment]
@posva 
Could you take a look at pr for this issue, please https://github.com/posva/unplugin-vue-router/pull/238

**Comment by Heunsig** [comment]
@posva Do you have any updates?

**Comment by tynliuk** [comment]
@posva, joining Heunsig's question, is there any update?
