### ISSUE TITLE
'"unplugin-vue-router"' has no exported member named 'VueRouterAutoImports'. 

### ISSUE THREAD

**Issue by sil2** [posva/unplugin-vue-router#67]
import { VueRouterAutoImports } from 'unplugin-vue-router'

'"unplugin-vue-router"' has no exported member named 'VueRouterAutoImports'. Did you mean 'VueRouterExports'?ts(2724)

also... Do you know how to add router.beforeEach((to, from). logic in router defined in vite.config.ts ?

im using AutoImport from unplugin-auto-import/vite ....

**Comment by posva** [comment]
Until a new version is released, use `VueRouterExports` (deprecated):

```diff
- VueRouterAutoImports
+ { 'vue-router/auto': VueRouterExports }
```
