### ISSUE TITLE
a way to define pee route query

### ISSUE THREAD

**Issue by zynth17** [posva/unplugin-vue-router#71]
is it now possible to define a safely typed route query?
i think would be good to have route query types, maybe define it on page level using the custom route block?

**Comment by posva** [comment]
It's not possible because the query can really be anything at all. In practice one should write a function to extract the query in a typesafe fashion:

```ts
const { page } = useRouteQuery({ page: Number })
page // ComputedRef<number | undefined>
```

But that is not something that should be handled here
