### ISSUE TITLE
Extract name and path from `definePage()`

### ISSUE THREAD

**Issue by posva** [posva/unplugin-vue-router#74]
Currently, name and path defined through `definePage()` are not added to the types like it happens with the route block but it should be possible since they are extracted through the AST

**Comment by zynth17** [comment]
any estimated time to fix on this? trying definePage today, but got error because it does not added to `typed-router.d.ts`

**Comment by posva** [comment]
This turns out to be really tricky: got the extraction working but I still have a few bugs to fix. I recommend you to stick to the `<route>` block for the moment. Note that definePage only accepts literals values as so:

```ts
definePage({ name: 'must be literal' })
```

I need to ensure that having imports doesn't have a huge impact on performance

**Comment by zynth17** [comment]
> This turns out to be really tricky: got the extraction working but I still have a few bugs to fix. I recommend you to stick to the `<route>` block for the moment. Note that definePage only accepts literals values as so:
> 
> ```ts
> definePage({ name: 'must be literal' })
> ```
> 
> I need to ensure that having imports doesn't have a huge impact on performance

all right! thanks :D

**Comment by zynth17** [comment]
any update on this? @posva

**Comment by posva** [comment]
I haven't been able to work on this feature again yet

**Comment by zynth17** [comment]
> I haven't been able to work on this feature again yet

all right, i hope this been fixed soon since it's really better to wrote everything using `definePage()` function rather than route block
