### ISSUE TITLE
Handle the normalization of paths in windows

### ISSUE THREAD

**Issue by posva** [posva/unplugin-vue-router#8]
Currently the plugin only works in POSIX environments, it needs to normalize some of the paths

**Comment by hannoeru** [comment]
Routes sort is also different in windows, so what I do in vite-plugin-pages is manually sort routes to pass the snapshot test, or maybe there is an other way to fix it.

**Comment by posva** [comment]
yeah, I saw that part also failed in tests 😆 
I think the sorting should happen at generation so people working across different os still get the same output. Using `pathe` to normalize the paths before generating the filepaths should be better
