### ISSUE TITLE
add SFC custom block for defining per route property

### ISSUE THREAD

**Issue by zynth17** [posva/unplugin-vue-router#9]
hello, can't wait for this package to officially release and stable.
right now i'm using [vite-plugin-pages](https://github.com/hannoeru/vite-plugin-pages) and i'm thinking to move to this package when it will be stable enough to use in production.
right now i can't seem to find a way to defining per route meta and property like naming and meta.
as on vite-plugin-pages we can add a custom route tag on route file. is it possible to also do this on unplugin-vue-router?
thankyou

here is example on how the vite-plugin-pages do it
```html
<route>
{
  name: "name-override",
  meta: {
    requiresAuth: false
  }
}
</route>
```

**Comment by posva** [comment]
This is planned. You can use extendRoutes at the moment

**Comment by zynth17** [comment]
> This is planned. You can use extendRoutes at the moment

great! will wait for this to be implemented. thankyou
