### ISSUE TITLE
Don't generate nested routes when no file name is the same as the folder name

### ISSUE THREAD

**Issue by zhiyuanzmj** [posva/unplugin-vue-router#90]
## What is Expected?
Provide an option to make it the same as the route structure generated by `nuxtjs` or `vite-plugin-pages`.

## Reproduction Link: 
https://stackblitz.com/edit/github-u3cz5i?file=nuxt.config.ts,pages%2Findex.vue,.gitignore
<img width="895" alt="image" src="https://user-images.githubusercontent.com/32807958/201572222-4e9c1983-a8da-4454-89d1-22357b767884.png">

**Comment by posva** [comment]
As mentioned in other issues, this works fine as this is a feature of vue router so adding an option seems unnecessary. Note you can still modify the array with `extendRoutes()` to fit your personal preferences. Do you have any particular use cases that cannot work with this vue-router routes structure?

**Comment by zhiyuanzmj** [comment]
``` ts
const router = createRouter({
  history: createWebHistory(import.meta.env.BASE_URL),
  extendRoutes(routes) {
    function unnestChildren(routes: RouteRecordRaw[]) {
      return routes.reduce((a, b) => {
        if (b.children?.length)
          b.children = unnestChildren(b.children)

        if (!b.component && b.children?.length) {
          a.push(
            ...b.children.map(i => ({
              ...i,
              path: b.path + (i.path ? `/${i.path}` : ''),
            })),
          )
        } else {
          a.push(b)
        }
        return a
      }, [] as RouteRecordRaw[])
    }
    return setupLayouts(unnestChildren(routes))
  },
})
``` ts
'extendRoutes' can resolved it, thank you.

**Comment by posva** [comment]
Thanks. Yeah, sidebars can be implemented in many ways and are therefore out of scope of vue-router and this plugin but they shouldn't be in the way either.
