### ISSUE TITLE
Export `getPageMap` api for other extend plugin

### ISSUE THREAD

**Issue by zhiyuanzmj** [posva/unplugin-vue-router#97]
I have a plugin [unplugin-vue-router-extend](https://github.com/zhiyuanzmj/unplugin-vue-router-extend) to automatically generated comonent's name:
<img width="1200" alt="image" src="https://user-images.githubusercontent.com/32807958/202403237-ae2d1ec0-1542-475a-b49d-e09d83d577ea.png">

But, I need `unplugin-vue-router` export `getPageMap` api to get component's name:
https://github.com/zhiyuanzmj/unplugin-vue-router-extend/blob/5bb465b9a127b88959720d1a1e8c1edb399b71c9/src/index.ts#L19

**Comment by posva** [comment]
As said in https://github.com/posva/unplugin-vue-router/issues/95#issuecomment-1316520678, I believe you should add the names individually to each component.

This request is not describing an existing problem, it's a personal preference **and there are many ways to set the component name** from the route name like the one described above (multitple times already) or override the names of the component in a `router.beforeResolve()`.

So please, if you open a feature request, put a bit more time into it so I can consider it. Exposing an internal property like the routeMap requires valid use cases not just personal preference. BTW, your solution doesn't work with named views as they would share the same name.
